from pydantic import BaseModel, field_validator
from typing import Optional
from datetime import datetime

class AddPaymentMethodRequest(BaseModel):
    """
    Add payment method request
    
    card_token is generated by Stripe.js on frontend
    """
    card_token: str  # tok_... from Stripe.js or pm_...
    provider: str = "stripe" # stripe or mercadopago
    set_as_default: bool = False
    
    @field_validator('card_token')
    @classmethod
    def validate_token(cls, v):
        # Allow Stripe (tok_, pm_) AND Mercado Pago (hex strings etc)
        # We rely on downstream clients to validate validity.
        if not v:
             raise ValueError('Token cannot be empty')
        return v

class PaymentMethodResponse(BaseModel):
    id: int
    card_brand: str
    card_last4: str
    card_exp_month: int
    card_exp_year: int
    is_default: bool
    is_active: bool
    is_expired: bool
    
    class Config:
        from_attributes = True

class PixPaymentResponse(BaseModel):
    payment_id: int
    amount: float
    qrcode_image: str
    qrcode_text: str
    expires_at: Optional[datetime]
