"""add_driver_wallet

Revision ID: 02f49fcd0089
Revises: 552339731b4c
Create Date: 2025-12-17 17:20:26.198075

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '02f49fcd0089'
down_revision: Union[str, None] = '552339731b4c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('driver_wallets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('driver_id', sa.UUID(), nullable=False),
    sa.Column('total_balance', sa.Numeric(precision=19, scale=4), nullable=False),
    sa.Column('held_balance', sa.Numeric(precision=19, scale=4), nullable=False),
    sa.Column('blocked_balance', sa.Numeric(precision=19, scale=4), nullable=False),
    sa.Column('available_balance', sa.Numeric(precision=19, scale=4), nullable=False),
    sa.Column('credit_balance', sa.Numeric(precision=19, scale=4), nullable=False),
    sa.Column('minimum_withdrawal', sa.Numeric(precision=19, scale=4), nullable=False),
    sa.Column('total_earned', sa.Numeric(precision=19, scale=4), nullable=False),
    sa.Column('total_withdrawn', sa.Numeric(precision=19, scale=4), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('available_balance >= 0', name='check_available_balance_positive'),
    sa.CheckConstraint('blocked_balance >= 0', name='check_blocked_balance_positive'),
    sa.CheckConstraint('credit_balance >= 0', name='check_credit_balance_positive'),
    sa.CheckConstraint('held_balance >= 0', name='check_held_balance_positive'),
    sa.CheckConstraint('total_balance >= 0', name='check_total_balance_positive'),
    sa.ForeignKeyConstraint(['driver_id'], ['drivers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_driver_wallets_driver_id'), 'driver_wallets', ['driver_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_drivers_location'), 'drivers', ['location'], unique=False, postgresql_using='gist')
    op.create_table('spatial_ref_sys',
    sa.Column('srid', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('auth_name', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.Column('auth_srid', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('srtext', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.Column('proj4text', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.CheckConstraint('srid > 0 AND srid <= 998999', name=op.f('spatial_ref_sys_srid_check')),
    sa.PrimaryKeyConstraint('srid', name=op.f('spatial_ref_sys_pkey'))
    )
    op.drop_index(op.f('ix_driver_wallets_driver_id'), table_name='driver_wallets')
    op.drop_table('driver_wallets')
    # ### end Alembic commands ###
