"""add_financial_events_table

Revision ID: 351c3695cc9e
Revises: df3c4d3527fb
Create Date: 2025-12-17 13:03:47.348493

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '351c3695cc9e'
down_revision: Union[str, None] = 'df3c4d3527fb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('financial_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.Enum('RIDE_PAYMENT', 'RIDE_EARNING', 'PLATFORM_COMMISSION', 'CANCELLATION_FEE', 'WALLET_DEPOSIT', 'WALLET_WITHDRAWAL', 'SETTLEMENT_HOLD', 'SETTLEMENT_RELEASE', 'PAYOUT_PROCESSING', 'PAYOUT_COMPLETED', 'PAYOUT_FAILED', 'ADJUSTMENT_DEBIT', 'ADJUSTMENT_CREDIT', 'REVERSAL', 'INCENTIVE_BONUS', 'INCENTIVE_CREDIT', name='eventtype'), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'COMPLETED', 'FAILED', 'REVERSED', name='eventstatus'), nullable=False),
    sa.Column('passenger_id', sa.UUID(), nullable=True),
    sa.Column('driver_id', sa.UUID(), nullable=True),
    sa.Column('ride_id', sa.UUID(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('reverses_event_id', sa.Integer(), nullable=True),
    sa.Column('reversed_by_event_id', sa.Integer(), nullable=True),
    sa.Column('external_transaction_id', sa.String(length=255), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('failed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['driver_id'], ['drivers.id'], ),
    sa.ForeignKeyConstraint(['passenger_id'], ['passengers.id'], ),
    sa.ForeignKeyConstraint(['reversed_by_event_id'], ['financial_events.id'], ),
    sa.ForeignKeyConstraint(['reverses_event_id'], ['financial_events.id'], ),
    sa.ForeignKeyConstraint(['ride_id'], ['rides.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_events_driver_completed', 'financial_events', ['driver_id', 'status', 'created_at'], unique=False)
    op.create_index('idx_events_passenger_completed', 'financial_events', ['passenger_id', 'status', 'created_at'], unique=False)
    op.create_index('idx_events_type_status', 'financial_events', ['event_type', 'status'], unique=False)
    op.create_index(op.f('ix_financial_events_driver_id'), 'financial_events', ['driver_id'], unique=False)
    op.create_index(op.f('ix_financial_events_event_type'), 'financial_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_financial_events_external_transaction_id'), 'financial_events', ['external_transaction_id'], unique=False)
    op.create_index(op.f('ix_financial_events_id'), 'financial_events', ['id'], unique=False)
    op.create_index(op.f('ix_financial_events_passenger_id'), 'financial_events', ['passenger_id'], unique=False)
    op.create_index(op.f('ix_financial_events_ride_id'), 'financial_events', ['ride_id'], unique=False)
    op.create_index(op.f('ix_financial_events_status'), 'financial_events', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_financial_events_status'), table_name='financial_events')
    op.drop_index(op.f('ix_financial_events_ride_id'), table_name='financial_events')
    op.drop_index(op.f('ix_financial_events_passenger_id'), table_name='financial_events')
    op.drop_index(op.f('ix_financial_events_id'), table_name='financial_events')
    op.drop_index(op.f('ix_financial_events_external_transaction_id'), table_name='financial_events')
    op.drop_index(op.f('ix_financial_events_event_type'), table_name='financial_events')
    op.drop_index(op.f('ix_financial_events_driver_id'), table_name='financial_events')
    op.drop_index('idx_events_type_status', table_name='financial_events')
    op.drop_index('idx_events_passenger_completed', table_name='financial_events')
    op.drop_index('idx_events_driver_completed', table_name='financial_events')
    op.drop_table('financial_events')
    # ### end Alembic commands ###
