"""add_mercadopago_columns

Revision ID: 377ad1536f6b
Revises: 39c914061dc4
Create Date: 2025-12-18 01:32:31.355150

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '377ad1536f6b'
down_revision: Union[str, None] = '39c914061dc4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_table('spatial_ref_sys') # Managed by PostGIS
    op.drop_index('ix_drivers_location', table_name='drivers', postgresql_using='gist')
    op.add_column('payment_methods', sa.Column('mercadopago_card_id', sa.String(length=255), nullable=True))
    op.add_column('payment_methods', sa.Column('provider', sa.String(length=50), nullable=False, server_default='stripe'))
    op.alter_column('payment_methods', 'stripe_payment_method_id',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.create_index(op.f('ix_payment_methods_mercadopago_card_id'), 'payment_methods', ['mercadopago_card_id'], unique=False)
    op.add_column('users', sa.Column('mercadopago_customer_id', sa.String(length=255), nullable=True))
    op.create_index(op.f('ix_users_mercadopago_customer_id'), 'users', ['mercadopago_customer_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_mercadopago_customer_id'), table_name='users')
    op.drop_column('users', 'mercadopago_customer_id')
    op.drop_index(op.f('ix_payment_methods_mercadopago_card_id'), table_name='payment_methods')
    op.alter_column('payment_methods', 'stripe_payment_method_id',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.drop_column('payment_methods', 'provider')
    op.drop_column('payment_methods', 'mercadopago_card_id')
    op.create_index('ix_drivers_location', 'drivers', ['location'], unique=False, postgresql_using='gist')
    op.create_table('spatial_ref_sys',
    sa.Column('srid', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('auth_name', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.Column('auth_srid', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('srtext', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.Column('proj4text', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.CheckConstraint('srid > 0 AND srid <= 998999', name='spatial_ref_sys_srid_check'),
    sa.PrimaryKeyConstraint('srid', name='spatial_ref_sys_pkey')
    )
    # ### end Alembic commands ###
