"""Add Card Payment Fields

Revision ID: 39c914061dc4
Revises: 189ee7f8eccb
Create Date: 2025-12-18 01:15:09.807093

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '39c914061dc4'
down_revision: Union[str, None] = '189ee7f8eccb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_table('spatial_ref_sys')
    # op.drop_index('ix_drivers_location', table_name='drivers', postgresql_using='gist')
    op.add_column('payments', sa.Column('payment_method_id', sa.Integer(), nullable=True))
    op.add_column('payments', sa.Column('stripe_payment_intent_id', sa.String(length=255), nullable=True))
    op.create_index(op.f('ix_payments_stripe_payment_intent_id'), 'payments', ['stripe_payment_intent_id'], unique=False)
    op.create_foreign_key(None, 'payments', 'payment_methods', ['payment_method_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'payments', type_='foreignkey')
    op.drop_index(op.f('ix_payments_stripe_payment_intent_id'), table_name='payments')
    op.drop_column('payments', 'stripe_payment_intent_id')
    op.drop_column('payments', 'payment_method_id')
    # op.create_index('ix_drivers_location', 'drivers', ['location'], unique=False, postgresql_using='gist')
    # op.create_table('spatial_ref_sys',
    # sa.Column('srid', sa.INTEGER(), autoincrement=False, nullable=False),
    # sa.Column('auth_name', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    # sa.Column('auth_srid', sa.INTEGER(), autoincrement=False, nullable=True),
    # sa.Column('srtext', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    # sa.Column('proj4text', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    # sa.CheckConstraint('srid > 0 AND srid <= 998999', name='spatial_ref_sys_srid_check'),
    # sa.PrimaryKeyConstraint('srid', name='spatial_ref_sys_pkey')
    # )
    # ### end Alembic commands ###
