"""add payments table

Revision ID: 552339731b4c
Revises: 4a0f6b6ad60d
Create Date: 2025-12-17 13:32:43.644801

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '552339731b4c'
down_revision: Union[str, None] = '4a0f6b6ad60d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ride_id', sa.UUID(), nullable=False),
    sa.Column('passenger_id', sa.UUID(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('payment_method', sa.String(length=50), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED', 'EXPIRED', name='paymentstatus'), nullable=False),
    sa.Column('pix_txid', sa.String(length=255), nullable=True),
    sa.Column('pix_qrcode_image', sa.Text(), nullable=True),
    sa.Column('pix_qrcode_text', sa.Text(), nullable=True),
    sa.Column('pix_expiration', sa.DateTime(timezone=True), nullable=True),
    sa.Column('external_transaction_id', sa.String(length=255), nullable=True),
    sa.Column('payment_event_id', sa.Integer(), nullable=True),
    sa.Column('earning_event_id', sa.Integer(), nullable=True),
    sa.Column('commission_event_id', sa.Integer(), nullable=True),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('failed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['commission_event_id'], ['financial_events.id'], ),
    sa.ForeignKeyConstraint(['earning_event_id'], ['financial_events.id'], ),
    sa.ForeignKeyConstraint(['passenger_id'], ['passengers.id'], ),
    sa.ForeignKeyConstraint(['payment_event_id'], ['financial_events.id'], ),
    sa.ForeignKeyConstraint(['ride_id'], ['rides.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payments_external_transaction_id'), 'payments', ['external_transaction_id'], unique=False)
    op.create_index(op.f('ix_payments_id'), 'payments', ['id'], unique=False)
    op.create_index(op.f('ix_payments_passenger_id'), 'payments', ['passenger_id'], unique=False)
    op.create_index(op.f('ix_payments_pix_txid'), 'payments', ['pix_txid'], unique=False)
    op.create_index(op.f('ix_payments_ride_id'), 'payments', ['ride_id'], unique=True)
    op.create_index(op.f('ix_payments_status'), 'payments', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_payments_ride_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_pix_txid'), table_name='payments')
    op.drop_index(op.f('ix_payments_passenger_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_external_transaction_id'), table_name='payments')
    op.drop_table('payments')
    # ### end Alembic commands ###
