"""Refactor Ledger Models

Revision ID: 976338111059
Revises: 0a0966ba1dc4
Create Date: 2025-12-17 02:23:11.631816

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '976338111059'
down_revision: Union[str, None] = '0a0966ba1dc4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ledger_entries_history',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('entry_id', sa.UUID(), nullable=False),
    sa.Column('transaction_id', sa.String(length=100), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('entry_type', sa.String(length=10), nullable=False),
    sa.Column('amount', sa.Numeric(precision=19, scale=6), nullable=False),
    sa.Column('change_type', sa.String(length=10), nullable=False),
    sa.Column('changed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['entry_id'], ['ledger_entries.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_ledger_history_entry', 'ledger_entries_history', ['entry_id'], unique=False)
    op.create_table('ledger_running_balances',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('driver_id', sa.UUID(), nullable=True),
    sa.Column('balance', sa.Numeric(precision=19, scale=6), nullable=False),
    sa.Column('last_entry_id', sa.UUID(), nullable=False),
    sa.Column('calculated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['ledger_accounts.id'], ),
    sa.ForeignKeyConstraint(['driver_id'], ['drivers.id'], ),
    sa.ForeignKeyConstraint(['last_entry_id'], ['ledger_entries.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_running_balance_account', 'ledger_running_balances', ['account_id'], unique=False)
    op.create_index('idx_running_balance_driver', 'ledger_running_balances', ['driver_id'], unique=False, postgresql_where=sa.text('driver_id IS NOT NULL'))
    
    # 1. Add 'code' as nullable first
    op.add_column('ledger_accounts', sa.Column('code', sa.String(length=20), nullable=True))
    op.add_column('ledger_accounts', sa.Column('description', sa.String(length=255), nullable=True))
    op.add_column('ledger_accounts', sa.Column('classification', sa.String(length=20), nullable=True))
    op.add_column('ledger_accounts', sa.Column('entity_id', sa.UUID(), nullable=True))
    op.add_column('ledger_accounts', sa.Column('entity_type', sa.String(length=50), nullable=True))
    op.add_column('ledger_accounts', sa.Column('is_active', sa.Boolean(), nullable=True))
    
    # 2. Backfill existing rows (if any)
    op.execute("UPDATE ledger_accounts SET code = 'LEG-' || substr(id::text, 1, 8) WHERE code IS NULL")
    
    # 3. Enforce Not Null on code
    op.alter_column('ledger_accounts', 'code', nullable=False)
    
    op.alter_column('ledger_accounts', 'balance',
               existing_type=sa.NUMERIC(precision=15, scale=2),
               type_=sa.Numeric(precision=19, scale=4),
               existing_nullable=True)
    op.create_unique_constraint(None, 'ledger_accounts', ['code'])
    
    op.add_column('ledger_entries', sa.Column('entry_type', sa.String(length=10), nullable=True)) # Nullable first
    op.execute("UPDATE ledger_entries SET entry_type = direction") # Copy direction to entry_type (assuming compat)
    # Actually direction was 'DEBIT'/'CREDIT', entry_type is same.
    # Set default if null?
    op.execute("UPDATE ledger_entries SET entry_type = 'DEBIT' WHERE entry_type IS NULL")
    op.alter_column('ledger_entries', 'entry_type', nullable=False)
    
    op.add_column('ledger_entries', sa.Column('reversed', sa.Boolean(), nullable=True))
    op.add_column('ledger_entries', sa.Column('reversal_entry_id', sa.UUID(), nullable=True))
    op.add_column('ledger_entries', sa.Column('posted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('ledger_entries', sa.Column('created_by', sa.UUID(), nullable=True))
    
    # Handle UUID -> String conversion
    op.alter_column('ledger_entries', 'transaction_id',
               existing_type=sa.UUID(),
               type_=sa.String(length=100),
               existing_nullable=False,
               postgresql_using='transaction_id::text')
               
    op.alter_column('ledger_entries', 'amount',
               existing_type=sa.NUMERIC(precision=15, scale=2),
               type_=sa.Numeric(precision=19, scale=4),
               existing_nullable=False)
    op.create_foreign_key(None, 'ledger_entries', 'ledger_entries', ['reversal_entry_id'], ['id'])
    op.create_foreign_key(None, 'ledger_entries', 'users', ['created_by'], ['id'])
    op.drop_column('ledger_entries', 'direction')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ledger_entries', sa.Column('direction', sa.VARCHAR(length=10), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'ledger_entries', type_='foreignkey')
    op.drop_constraint(None, 'ledger_entries', type_='foreignkey')
    op.alter_column('ledger_entries', 'amount',
               existing_type=sa.Numeric(precision=19, scale=4),
               type_=sa.NUMERIC(precision=15, scale=2),
               existing_nullable=False)
    op.alter_column('ledger_entries', 'transaction_id',
               existing_type=sa.String(length=100),
               type_=sa.UUID(),
               existing_nullable=False)
    op.drop_column('ledger_entries', 'created_by')
    op.drop_column('ledger_entries', 'posted_at')
    op.drop_column('ledger_entries', 'reversal_entry_id')
    op.drop_column('ledger_entries', 'reversed')
    op.drop_column('ledger_entries', 'entry_type')
    op.drop_constraint(None, 'ledger_accounts', type_='unique')
    op.alter_column('ledger_accounts', 'balance',
               existing_type=sa.Numeric(precision=19, scale=4),
               type_=sa.NUMERIC(precision=15, scale=2),
               existing_nullable=True)
    op.drop_column('ledger_accounts', 'is_active')
    op.drop_column('ledger_accounts', 'entity_type')
    op.drop_column('ledger_accounts', 'entity_id')
    op.drop_column('ledger_accounts', 'classification')
    op.drop_column('ledger_accounts', 'description')
    op.drop_column('ledger_accounts', 'code')
    op.drop_index('idx_running_balance_driver', table_name='ledger_running_balances', postgresql_where=sa.text('driver_id IS NOT NULL'))
    op.drop_index('idx_running_balance_account', table_name='ledger_running_balances')
    op.drop_table('ledger_running_balances')
    op.drop_index('idx_ledger_history_entry', table_name='ledger_entries_history')
    op.drop_table('ledger_entries_history')
    # ### end Alembic commands ###
