"""add_route_polyline_to_rides

Revision ID: a7270428583e
Revises: 037fa9810bfe
Create Date: 2025-12-17 11:52:30.944726

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a7270428583e'
down_revision: Union[str, None] = '037fa9810bfe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_table('spatial_ref_sys') # Skip PostGIS table
    # op.drop_index(op.f('ix_drivers_location'), table_name='drivers', postgresql_using='gist') # Skip existing index
    op.add_column('rides', sa.Column('route_polyline', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rides', 'route_polyline')
    # op.create_index(op.f('ix_drivers_location'), 'drivers', ['location'], unique=False, postgresql_using='gist')
    # op.create_table('spatial_ref_sys', ...)
    # ### end Alembic commands ###
